# Generated by Django 2.2 on 2019-04-22 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Name')),
                ('plan', models.CharField(max_length=20, verbose_name='Plan')),
                ('description', models.CharField(max_length=5500, verbose_name='Description')),
                ('correlative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Career')),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Name')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Career')),
                ('correlative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Matter')),
            ],
            options={
                'verbose_name': 'Matter',
                'verbose_name_plural': 'Matters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Name')),
                ('max_students', models.IntegerField(blank=True, null=True, verbose_name='Maximum Students')),
                ('min_students', models.IntegerField(blank=True, null=True, verbose_name='Minimum Students')),
                ('matter', models.ManyToManyField(to='campus.Matter')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=550, verbose_name='Name')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Maximum Capacity')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Branch')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classroom',
                'ordering': ['code'],
            },
        ),
    ]
